const lang = {
    en: {
        signIn: "Sign In",
        signUp: "Sign Up",
        signOut: "Sign Out",
        newtoAstroGPT: "New to AstroGPT?",
        password: "Password",
        email: "Email Address",
        name: "Full Name",
        alreadyAcc: "Already have an account?",
        welcome: "Welcome to",
        astroGPT: "AstroGPT",
        gptSearch: "GPT Search",
        loginDescription: "Connect with astrologers, chat seamlessly, get personalized horoscopes with Astrobot. Unlock insights with Kundli from AstroKundli",
        explore: "AstroBot",
        chat: "Chat with Astrologers",
        call: "Call to Astrologers",
        search: "Search for Astrologers",
        filter: "Filter",
        all: "All",
        topRated: "Top rated",
        offer: "Offer",
        vedic: "Vedic",
        numerology: "Numerology",
        tarot: "Tarot",
        faceReading: "Face Reading",
        vastu: "Vastu",
        lifeCoach: "Life Coach",
        psychologist: "Psychologist",
        palmistry: "Palmistry",
        orders: "Orders",
        exp: "Exp",
        years: "Years",
        min: "min",
    },
    hindi: {
        signIn: "दाखिल करें",
        signUp: "साइन अप करें",
        signOut: "साइन आउट",
        newtoAstroGPT: "आस्ट्रोजीपीटी पर नए हैं?",
        password: "पासवर्ड",
        email: "मेल पता",
        name: "पूरा नाम",
        alreadyAcc: "क्या आपके पास पहले से एक खाता मौजूद है?",
        welcome: "स्वागत करते हैं",
        astroGPT: "AstroGPT",
        gptSearch: "जीपीटी खोज",
        loginDescription: "ज्योतिषियों से जुड़ें, बिना किसी समस्या के चैट करें, व्यक्तिगत राशिफल प्राप्त करें, और आज ही हमारे सहज चैटबॉट के साथ अपनी खगोलीय यात्रा शुरू करें",
        explore: "अन्वेषण करें",
        chat: "ज्योतिषियों के साथ चैट करें",
        call: "ज्योतिषियों को कॉल करें",
        search: "ज्योतिषियों के लिए खोजें",
        filter: "फ़िल्टर",
        all: "सभी",
        topRated: "शीर्ष रेटेड",
        offer: "ऑफर",
        vedic: "वैदिक",
        numerology: "न्यूमेरोलॉजी",
        tarot: "तारो",
        faceReading: "फेस रीडिंग",
        vastu: "वास्तु",
        lifeCoach: "लाइफ कोच",
        psychologist: "मनोविज्ञानी",
        palmistry: "हस्तरेखा",
        orders: "आदेश",
        exp: "अनुभव",
        years: "वर्ष",
        min: "मिनट",
    },
    marathi: {
        signIn: "साइन इन करा",
        signUp: "साइन अप करा",
        signOut: "साइन आउट करा",
        newtoAstroGPT: "आस्ट्रोजीपीटी वर नवीन?",
        password: "पासवर्ड",
        email: "ईमेल पत्ता",
        name: "पूर्ण नाव",
        alreadyAcc: "आधीपासूनच एक खाते आहे?",
        welcome: "स्वागत आहे",
        astroGPT: "AstroGPT",
        gptSearch: "GPT शोध",
        loginDescription: "ज्योतिषियों संबंधित व्यक्तींसोंसोबत चैट करा, साधारण राशिफल प्राप्त करा, आणि आज आमच्या सहज चॅटबॉटसह आपले खगोलविज्ञानिक यात्रा सुरू करा",
        explore: "शोधा",
        chat: "ज्योतिषाशी चॅट करा",
        call: "ज्योतिषांना कॉल करा",
        search: "ज्योतिषांसाठी शोधा",
        filter: "फिल्टर",
        all: "सर्व",
        topRated: "टॉप दर्जा",
        offer: "ऑफर",
        vedic: "वैदिक",
        numerology: "संख्याशास्त्र",
        tarot: "तारो",
        faceReading: "चेहरा वाचन",
        vastu: "वास्तू",
        lifeCoach: "जीवन कोच",
        psychologist: "मनोवैज्ञानिक",
        palmistry: "हस्तरेखा विज्ञान",
        orders: "ऑर्डर्स",
        exp: "अनुभव",
        years: "वर्षे",
        min: "मिनिट्स",
    },
    spanish: {
        signIn: "Iniciar sesión",
        signUp: "Inscribirse",
        signOut: "Desconectar",
        newtoAstroGPT: "¿Nuevo en AstroGPT?",
        password: "Contraseña",
        email: "Dirección de correo electrónico",
        name: "Nombre completo",
        alreadyAcc: "¿Ya tienes una cuenta?",
        welcome: "Bienvenido a",
        astroGPT: "AstroGPT",
        gptSearch: "Búsqueda GPT",
        loginDescription: "Conéctese con astrólogos, chatee sin problemas, obtenga horóscopos personalizados y comience su viaje cósmico hoy mismo con nuestro intuitivo chatbot",
        explore: "Explorar",
        chat: "Chatear con astrólogos",
        call: "Llamar a astrólogos",
        search: "Buscar astrólogos",
        filter: "Filtrar",
        all: "Todos",
        topRated: "Más valorados",
        offer: "Oferta",
        vedic: "Védico",
        numerology: "Numerología",
        tarot: "Tarot",
        faceReading: "Lectura de rostro",
        vastu: "Vastu",
        lifeCoach: "Entrenador de vida",
        psychologist: "Psicólogo",
        palmistry: "Quiromancia",
        orders: "Pedidos",
        exp: "Exp",
        years: "Años",
        min: "min",
    },
    japanese: {
        signIn: "サインイン",
        signUp: "サインアップ",
        signOut: "サインアウト",
        newtoAstroGPT: "アストロGPT は初めてですか？",
        password: "パスワード",
        email: "メールアドレス",
        name: "フルネーム",
        alreadyAcc: "すでにアカウントをお持ちですか？",
        welcome: "ようこそ",
        astroGPT: "アストロGPT",
        gptSearch: "GPT 検索",
        loginDescription: "占星術師とつながり、シームレスにチャットし、パーソナライズされた星座占いを入手し、直感的なチャットボットと一緒に今日から宇宙の旅を始めましょう",
        explore: "探検する",
        chat: "占星術師とチャット",
        call: "占星術師に電話",
        search: "占星術師を検索",
        filter: "フィルター",
        all: "すべて",
        topRated: "トップ評価",
        offer: "オファー",
        vedic: "ヴェーダ",
        numerology: "数秘術",
        tarot: "タロット",
        faceReading: "顔の読み取り",
        vastu: "ヴァーストゥ",
        lifeCoach: "ライフコーチ",
        psychologist: "心理学者",
        palmistry: "手相学",
        orders: "注文",
        exp: "経験",
        years: "年",
    },
    telugu: {
        signIn: "సైన్ ఇన్",
        signUp: "సైన్ అప్",
        signOut: "సైన్ ఔట్",
        newtoAstroGPT: "ఆస్ట్రోGPT లో హొసకు వచ్చారా?",
        password: "పాస్‌వర్డ్",
        email: "ఇమెయిల్ చిరునామా",
        name: "పూర్తి పేరు",
        alreadyAcc: "ముందుగా ఖాతా ఉందా?",
        welcome: "స్వాగతం",
        astroGPT: "ఆస్ట్రోGPT",
        gptSearch: "GPT వెతికి",
        loginDescription: "జ్యోతిషులతో కనెక్ట్ అవుట్ అనుకుంటున్నారా, సీమలోకి చాట్ చేయండి, వ్యక్తిగత జాతకాలు పొందండి, మరియు మా సూక్ష్మమైన చాట్‌బాట్‌తో మీ ఖగోళ ప్రయాణం ఈ రోజు ప్రారంభించండి",
        explore: "అన్వేషించండి",
        chat: "జ్యోతిషులతో చాట్",
        call: "జ్యోతిషులను కాల్ చేయండి",
        search: "జ్యోతిషులను శోధించండి",
        filter: "వడపోలి",
        all: "అన్ని",
        topRated: "ప్రముఖ రేటెడ్",
        offer: "ఆఫర్",
        vedic: "వెదిక్",
        numerology: "న్యూమరాలజీ",
        tarot: "తారోట్",
        faceReading: "ఫేస్ రీడింగ్",
        vastu: "వాస్తు",
        lifeCoach: "జీవన కోచ్",
        psychologist: "మానసిక శాస్త్రజ్ఞుడు",
        palmistry: "హస్తరేఖ",
        orders: "ఆర్డర్‌లు",
        exp: "అనుభవం",
        years: "సంవత్సరాలు",
        min: "నిమిషాలు",
    }
};

export default lang;
